name: "Build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        env:
          NEXT_PUBLIC_TYPESENSE_API_KEY: ${{ secrets.NEXT_PUBLIC_TYPESENSE.API.KEY }}
          NEXT_PUBLIC_CHAT_API: ${{ secrets.NEXT_PUBLIC_CHAT_API }}
        run: bun next build
